<?php
// Call UNL_Services_PeoplefinderTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "UNL_Services_PeoplefinderTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once 'UNL/Services/Peoplefinder.php';

/**
 * Test class for UNL_Services_Peoplefinder.
 * Generated by PHPUnit_Util_Skeleton on 2007-04-13 at 10:19:55.
 */
class UNL_Services_PeoplefinderTest extends PHPUnit_Framework_TestCase {
    
    public $uid = 'bbieber2';
    
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("UNL_Services_PeoplefinderTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testGetFullName().
     */
    public function testGetFullName() {
        // Remove the following line when you implement this test.
        $this->markTestIncomplete(
          "This test has not been implemented yet."
        );
    }

    /**
     * @todo Implement testGetEmail().
     */
    public function testGetEmail() {
        $this->assertEquals('bbieber2@unl.edu',UNL_Services_Peoplefinder::getEmail($this->uid));
    }

    /**
     * @todo Implement testGetHCard().
     */
    public function testGetHCard() {
        $this->assertEquals(file_get_contents('http://peoplefinder.unl.edu/hcards/'.$this->uid),
                UNL_Services_Peoplefinder::getHCard($this->uid));
    }

    /**
     * @todo Implement testGetVCard().
     */
    public function testGetVCard() {
        // Remove the following line when you implement this test.
        $this->markTestIncomplete(
          "This test has not been implemented yet."
        );
    }
}

// Call UNL_Services_PeoplefinderTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "UNL_Services_PeoplefinderTest::main") {
    UNL_Services_PeoplefinderTest::main();
}
?>
